// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chacha20_poly1305.proto

package com.google.crypto.tink.proto;

/**
 * <pre>
 * key_type: type.googleapis.com/google.crypto.tink.ChaCha20Poly1305.
 * This key type actually implements ChaCha20Poly1305 as described
 * at https://tools.ietf.org/html/rfc7539#section-2.8.
 * </pre>
 *
 * Protobuf type {@code google.crypto.tink.ChaCha20Poly1305Key}
 */
public final class ChaCha20Poly1305Key extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.crypto.tink.ChaCha20Poly1305Key)
    ChaCha20Poly1305KeyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChaCha20Poly1305Key.newBuilder() to construct.
  private ChaCha20Poly1305Key(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChaCha20Poly1305Key() {
    keyValue_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChaCha20Poly1305Key();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.crypto.tink.proto.Chacha20Poly1305.internal_static_google_crypto_tink_ChaCha20Poly1305Key_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.crypto.tink.proto.Chacha20Poly1305.internal_static_google_crypto_tink_ChaCha20Poly1305Key_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.crypto.tink.proto.ChaCha20Poly1305Key.class, com.google.crypto.tink.proto.ChaCha20Poly1305Key.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int KEY_VALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString keyValue_;
  /**
   * <code>bytes key_value = 2;</code>
   * @return The keyValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getKeyValue() {
    return keyValue_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeUInt32(1, version_);
    }
    if (!keyValue_.isEmpty()) {
      output.writeBytes(2, keyValue_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, version_);
    }
    if (!keyValue_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, keyValue_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.crypto.tink.proto.ChaCha20Poly1305Key)) {
      return super.equals(obj);
    }
    com.google.crypto.tink.proto.ChaCha20Poly1305Key other = (com.google.crypto.tink.proto.ChaCha20Poly1305Key) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!getKeyValue()
        .equals(other.getKeyValue())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + KEY_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getKeyValue().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.crypto.tink.proto.ChaCha20Poly1305Key prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * key_type: type.googleapis.com/google.crypto.tink.ChaCha20Poly1305.
   * This key type actually implements ChaCha20Poly1305 as described
   * at https://tools.ietf.org/html/rfc7539#section-2.8.
   * </pre>
   *
   * Protobuf type {@code google.crypto.tink.ChaCha20Poly1305Key}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.crypto.tink.ChaCha20Poly1305Key)
      com.google.crypto.tink.proto.ChaCha20Poly1305KeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.crypto.tink.proto.Chacha20Poly1305.internal_static_google_crypto_tink_ChaCha20Poly1305Key_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.crypto.tink.proto.Chacha20Poly1305.internal_static_google_crypto_tink_ChaCha20Poly1305Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.crypto.tink.proto.ChaCha20Poly1305Key.class, com.google.crypto.tink.proto.ChaCha20Poly1305Key.Builder.class);
    }

    // Construct using com.google.crypto.tink.proto.ChaCha20Poly1305Key.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      keyValue_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.crypto.tink.proto.Chacha20Poly1305.internal_static_google_crypto_tink_ChaCha20Poly1305Key_descriptor;
    }

    @java.lang.Override
    public com.google.crypto.tink.proto.ChaCha20Poly1305Key getDefaultInstanceForType() {
      return com.google.crypto.tink.proto.ChaCha20Poly1305Key.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.crypto.tink.proto.ChaCha20Poly1305Key build() {
      com.google.crypto.tink.proto.ChaCha20Poly1305Key result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.crypto.tink.proto.ChaCha20Poly1305Key buildPartial() {
      com.google.crypto.tink.proto.ChaCha20Poly1305Key result = new com.google.crypto.tink.proto.ChaCha20Poly1305Key(this);
      result.version_ = version_;
      result.keyValue_ = keyValue_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.crypto.tink.proto.ChaCha20Poly1305Key) {
        return mergeFrom((com.google.crypto.tink.proto.ChaCha20Poly1305Key)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.crypto.tink.proto.ChaCha20Poly1305Key other) {
      if (other == com.google.crypto.tink.proto.ChaCha20Poly1305Key.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getKeyValue() != com.google.protobuf.ByteString.EMPTY) {
        setKeyValue(other.getKeyValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              version_ = input.readUInt32();

              break;
            } // case 8
            case 18: {
              keyValue_ = input.readBytes();

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int version_ ;
    /**
     * <code>uint32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>uint32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString keyValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes key_value = 2;</code>
     * @return The keyValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKeyValue() {
      return keyValue_;
    }
    /**
     * <code>bytes key_value = 2;</code>
     * @param value The keyValue to set.
     * @return This builder for chaining.
     */
    public Builder setKeyValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      keyValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes key_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyValue() {
      
      keyValue_ = getDefaultInstance().getKeyValue();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.crypto.tink.ChaCha20Poly1305Key)
  }

  // @@protoc_insertion_point(class_scope:google.crypto.tink.ChaCha20Poly1305Key)
  private static final com.google.crypto.tink.proto.ChaCha20Poly1305Key DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.crypto.tink.proto.ChaCha20Poly1305Key();
  }

  public static com.google.crypto.tink.proto.ChaCha20Poly1305Key getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChaCha20Poly1305Key>
      PARSER = new com.google.protobuf.AbstractParser<ChaCha20Poly1305Key>() {
    @java.lang.Override
    public ChaCha20Poly1305Key parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChaCha20Poly1305Key> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChaCha20Poly1305Key> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.crypto.tink.proto.ChaCha20Poly1305Key getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

