// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chacha20_poly1305.proto

package com.google.crypto.tink.proto;

public interface ChaCha20Poly1305KeyFormatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.ChaCha20Poly1305KeyFormat)
    com.google.protobuf.MessageOrBuilder {
}
