// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/common.proto

package com.google.crypto.tink.proto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/common.proto\022\022google.crypto.tink" +
      "*c\n\021EllipticCurveType\022\021\n\rUNKNOWN_CURVE\020\000" +
      "\022\r\n\tNIST_P256\020\002\022\r\n\tNIST_P384\020\003\022\r\n\tNIST_P" +
      "521\020\004\022\016\n\nCURVE25519\020\005*j\n\rEcPointFormat\022\022" +
      "\n\016UNKNOWN_FORMAT\020\000\022\020\n\014UNCOMPRESSED\020\001\022\016\n\n" +
      "COMPRESSED\020\002\022#\n\037DO_NOT_USE_CRUNCHY_UNCOM" +
      "PRESSED\020\003*V\n\010HashType\022\020\n\014UNKNOWN_HASH\020\000\022" +
      "\010\n\004SHA1\020\001\022\n\n\006SHA384\020\002\022\n\n\006SHA256\020\003\022\n\n\006SHA" +
      "512\020\004\022\n\n\006SHA224\020\005BQ\n\034com.google.crypto.t" +
      "ink.protoP\001Z/github.com/google/tink/go/p" +
      "roto/common_go_protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
