// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ecdsa.proto

package com.google.crypto.tink.proto;

public final class Ecdsa {
  private Ecdsa() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_EcdsaParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_EcdsaParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_EcdsaPublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_EcdsaPublicKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_EcdsaPrivateKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_EcdsaPrivateKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_EcdsaKeyFormat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_EcdsaKeyFormat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/ecdsa.proto\022\022google.crypto.tink\032" +
      "\022proto/common.proto\"\262\001\n\013EcdsaParams\022/\n\th" +
      "ash_type\030\001 \001(\0162\034.google.crypto.tink.Hash" +
      "Type\0224\n\005curve\030\002 \001(\0162%.google.crypto.tink" +
      ".EllipticCurveType\022<\n\010encoding\030\003 \001(\0162*.g" +
      "oogle.crypto.tink.EcdsaSignatureEncoding" +
      "\"h\n\016EcdsaPublicKey\022\017\n\007version\030\001 \001(\r\022/\n\006p" +
      "arams\030\002 \001(\0132\037.google.crypto.tink.EcdsaPa" +
      "rams\022\t\n\001x\030\003 \001(\014\022\t\n\001y\030\004 \001(\014\"m\n\017EcdsaPriva" +
      "teKey\022\017\n\007version\030\001 \001(\r\0226\n\npublic_key\030\002 \001" +
      "(\0132\".google.crypto.tink.EcdsaPublicKey\022\021" +
      "\n\tkey_value\030\003 \001(\014\"R\n\016EcdsaKeyFormat\022/\n\006p" +
      "arams\030\002 \001(\0132\037.google.crypto.tink.EcdsaPa" +
      "rams\022\017\n\007version\030\003 \001(\r*G\n\026EcdsaSignatureE" +
      "ncoding\022\024\n\020UNKNOWN_ENCODING\020\000\022\016\n\nIEEE_P1" +
      "363\020\001\022\007\n\003DER\020\002BP\n\034com.google.crypto.tink" +
      ".protoP\001Z.github.com/google/tink/go/prot" +
      "o/ecdsa_go_protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.crypto.tink.proto.Common.getDescriptor(),
        });
    internal_static_google_crypto_tink_EcdsaParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_crypto_tink_EcdsaParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_EcdsaParams_descriptor,
        new java.lang.String[] { "HashType", "Curve", "Encoding", });
    internal_static_google_crypto_tink_EcdsaPublicKey_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_crypto_tink_EcdsaPublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_EcdsaPublicKey_descriptor,
        new java.lang.String[] { "Version", "Params", "X", "Y", });
    internal_static_google_crypto_tink_EcdsaPrivateKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_crypto_tink_EcdsaPrivateKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_EcdsaPrivateKey_descriptor,
        new java.lang.String[] { "Version", "PublicKey", "KeyValue", });
    internal_static_google_crypto_tink_EcdsaKeyFormat_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_crypto_tink_EcdsaKeyFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_EcdsaKeyFormat_descriptor,
        new java.lang.String[] { "Params", "Version", });
    com.google.crypto.tink.proto.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
