// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/common.proto

package com.google.crypto.tink.proto;

/**
 * Protobuf enum {@code google.crypto.tink.EcPointFormat}
 */
public enum EcPointFormat
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_FORMAT = 0;</code>
   */
  UNKNOWN_FORMAT(0),
  /**
   * <code>UNCOMPRESSED = 1;</code>
   */
  UNCOMPRESSED(1),
  /**
   * <code>COMPRESSED = 2;</code>
   */
  COMPRESSED(2),
  /**
   * <pre>
   * Like UNCOMPRESSED but without the &#92;x04 prefix. Crunchy uses this format.
   * DO NOT USE unless you are a Crunchy user moving to Tink.
   * </pre>
   *
   * <code>DO_NOT_USE_CRUNCHY_UNCOMPRESSED = 3;</code>
   */
  DO_NOT_USE_CRUNCHY_UNCOMPRESSED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_FORMAT = 0;</code>
   */
  public static final int UNKNOWN_FORMAT_VALUE = 0;
  /**
   * <code>UNCOMPRESSED = 1;</code>
   */
  public static final int UNCOMPRESSED_VALUE = 1;
  /**
   * <code>COMPRESSED = 2;</code>
   */
  public static final int COMPRESSED_VALUE = 2;
  /**
   * <pre>
   * Like UNCOMPRESSED but without the &#92;x04 prefix. Crunchy uses this format.
   * DO NOT USE unless you are a Crunchy user moving to Tink.
   * </pre>
   *
   * <code>DO_NOT_USE_CRUNCHY_UNCOMPRESSED = 3;</code>
   */
  public static final int DO_NOT_USE_CRUNCHY_UNCOMPRESSED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EcPointFormat valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static EcPointFormat forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_FORMAT;
      case 1: return UNCOMPRESSED;
      case 2: return COMPRESSED;
      case 3: return DO_NOT_USE_CRUNCHY_UNCOMPRESSED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EcPointFormat>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EcPointFormat> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EcPointFormat>() {
          public EcPointFormat findValueByNumber(int number) {
            return EcPointFormat.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.crypto.tink.proto.Common.getDescriptor().getEnumTypes().get(1);
  }

  private static final EcPointFormat[] VALUES = values();

  public static EcPointFormat valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EcPointFormat(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.crypto.tink.EcPointFormat)
}

