// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ed25519.proto

package com.google.crypto.tink.proto;

public interface Ed25519PrivateKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.Ed25519PrivateKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required.
   * </pre>
   *
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * The private key is 32 bytes of cryptographically secure random data.
   * See https://tools.ietf.org/html/rfc8032#section-5.1.5.
   * Required.
   * </pre>
   *
   * <code>bytes key_value = 2;</code>
   * @return The keyValue.
   */
  com.google.protobuf.ByteString getKeyValue();

  /**
   * <pre>
   * The corresponding public key.
   * </pre>
   *
   * <code>.google.crypto.tink.Ed25519PublicKey public_key = 3;</code>
   * @return Whether the publicKey field is set.
   */
  boolean hasPublicKey();
  /**
   * <pre>
   * The corresponding public key.
   * </pre>
   *
   * <code>.google.crypto.tink.Ed25519PublicKey public_key = 3;</code>
   * @return The publicKey.
   */
  com.google.crypto.tink.proto.Ed25519PublicKey getPublicKey();
  /**
   * <pre>
   * The corresponding public key.
   * </pre>
   *
   * <code>.google.crypto.tink.Ed25519PublicKey public_key = 3;</code>
   */
  com.google.crypto.tink.proto.Ed25519PublicKeyOrBuilder getPublicKeyOrBuilder();
}
