// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ed25519.proto

package com.google.crypto.tink.proto;

public final class Ed25519 {
  private Ed25519() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_Ed25519KeyFormat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_Ed25519KeyFormat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_Ed25519PublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_Ed25519PublicKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_Ed25519PrivateKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_Ed25519PrivateKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/ed25519.proto\022\022google.crypto.tin" +
      "k\"#\n\020Ed25519KeyFormat\022\017\n\007version\030\001 \001(\r\"6" +
      "\n\020Ed25519PublicKey\022\017\n\007version\030\001 \001(\r\022\021\n\tk" +
      "ey_value\030\002 \001(\014\"q\n\021Ed25519PrivateKey\022\017\n\007v" +
      "ersion\030\001 \001(\r\022\021\n\tkey_value\030\002 \001(\014\0228\n\npubli" +
      "c_key\030\003 \001(\0132$.google.crypto.tink.Ed25519" +
      "PublicKeyBR\n\034com.google.crypto.tink.prot" +
      "oP\001Z0github.com/google/tink/go/proto/ed2" +
      "5519_go_protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_crypto_tink_Ed25519KeyFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_crypto_tink_Ed25519KeyFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_Ed25519KeyFormat_descriptor,
        new java.lang.String[] { "Version", });
    internal_static_google_crypto_tink_Ed25519PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_crypto_tink_Ed25519PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_Ed25519PublicKey_descriptor,
        new java.lang.String[] { "Version", "KeyValue", });
    internal_static_google_crypto_tink_Ed25519PrivateKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_crypto_tink_Ed25519PrivateKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_Ed25519PrivateKey_descriptor,
        new java.lang.String[] { "Version", "KeyValue", "PublicKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
