// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ed25519.proto

package com.google.crypto.tink.proto;

public interface Ed25519KeyFormatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.Ed25519KeyFormat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();
}
