// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ed25519.proto

package com.google.crypto.tink.proto;

public interface Ed25519PublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.Ed25519PublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required.
   * </pre>
   *
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * The public key is 32 bytes, encoded according to
   * https://tools.ietf.org/html/rfc8032#section-5.1.2.
   * Required.
   * </pre>
   *
   * <code>bytes key_value = 2;</code>
   * @return The keyValue.
   */
  com.google.protobuf.ByteString getKeyValue();
}
