// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/tink.proto

package com.google.crypto.tink.proto;

public interface EncryptedKeysetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.EncryptedKeyset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required.
   * </pre>
   *
   * <code>bytes encrypted_keyset = 2;</code>
   * @return The encryptedKeyset.
   */
  com.google.protobuf.ByteString getEncryptedKeyset();

  /**
   * <pre>
   * Optional.
   * </pre>
   *
   * <code>.google.crypto.tink.KeysetInfo keyset_info = 3;</code>
   * @return Whether the keysetInfo field is set.
   */
  boolean hasKeysetInfo();
  /**
   * <pre>
   * Optional.
   * </pre>
   *
   * <code>.google.crypto.tink.KeysetInfo keyset_info = 3;</code>
   * @return The keysetInfo.
   */
  com.google.crypto.tink.proto.KeysetInfo getKeysetInfo();
  /**
   * <pre>
   * Optional.
   * </pre>
   *
   * <code>.google.crypto.tink.KeysetInfo keyset_info = 3;</code>
   */
  com.google.crypto.tink.proto.KeysetInfoOrBuilder getKeysetInfoOrBuilder();
}
