// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/tink.proto

package com.google.crypto.tink.proto;

/**
 * Protobuf enum {@code google.crypto.tink.KeyStatusType}
 */
public enum KeyStatusType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_STATUS = 0;</code>
   */
  UNKNOWN_STATUS(0),
  /**
   * <pre>
   * Can be used for crypto operations.
   * </pre>
   *
   * <code>ENABLED = 1;</code>
   */
  ENABLED(1),
  /**
   * <pre>
   * Cannot be used, but exists and can become ENABLED.
   * </pre>
   *
   * <code>DISABLED = 2;</code>
   */
  DISABLED(2),
  /**
   * <pre>
   * Key data does not exist in this Keyset any more.
   * </pre>
   *
   * <code>DESTROYED = 3;</code>
   */
  DESTROYED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_STATUS = 0;</code>
   */
  public static final int UNKNOWN_STATUS_VALUE = 0;
  /**
   * <pre>
   * Can be used for crypto operations.
   * </pre>
   *
   * <code>ENABLED = 1;</code>
   */
  public static final int ENABLED_VALUE = 1;
  /**
   * <pre>
   * Cannot be used, but exists and can become ENABLED.
   * </pre>
   *
   * <code>DISABLED = 2;</code>
   */
  public static final int DISABLED_VALUE = 2;
  /**
   * <pre>
   * Key data does not exist in this Keyset any more.
   * </pre>
   *
   * <code>DESTROYED = 3;</code>
   */
  public static final int DESTROYED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static KeyStatusType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static KeyStatusType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_STATUS;
      case 1: return ENABLED;
      case 2: return DISABLED;
      case 3: return DESTROYED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<KeyStatusType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      KeyStatusType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<KeyStatusType>() {
          public KeyStatusType findValueByNumber(int number) {
            return KeyStatusType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.google.crypto.tink.proto.Tink.getDescriptor().getEnumTypes().get(0);
  }

  private static final KeyStatusType[] VALUES = values();

  public static KeyStatusType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private KeyStatusType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.crypto.tink.KeyStatusType)
}

