// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/tink.proto

package com.google.crypto.tink.proto;

public interface KeysetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.Keyset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifies key used to generate new crypto data (encrypt, sign).
   * Required.
   * </pre>
   *
   * <code>uint32 primary_key_id = 1;</code>
   * @return The primaryKeyId.
   */
  int getPrimaryKeyId();

  /**
   * <pre>
   * Actual keys in the Keyset.
   * Required.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.Keyset.Key key = 2;</code>
   */
  java.util.List<com.google.crypto.tink.proto.Keyset.Key> 
      getKeyList();
  /**
   * <pre>
   * Actual keys in the Keyset.
   * Required.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.Keyset.Key key = 2;</code>
   */
  com.google.crypto.tink.proto.Keyset.Key getKey(int index);
  /**
   * <pre>
   * Actual keys in the Keyset.
   * Required.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.Keyset.Key key = 2;</code>
   */
  int getKeyCount();
  /**
   * <pre>
   * Actual keys in the Keyset.
   * Required.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.Keyset.Key key = 2;</code>
   */
  java.util.List<? extends com.google.crypto.tink.proto.Keyset.KeyOrBuilder> 
      getKeyOrBuilderList();
  /**
   * <pre>
   * Actual keys in the Keyset.
   * Required.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.Keyset.Key key = 2;</code>
   */
  com.google.crypto.tink.proto.Keyset.KeyOrBuilder getKeyOrBuilder(
      int index);
}
