// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/tink.proto

package com.google.crypto.tink.proto;

public interface KeysetInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.KeysetInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * See Keyset.primary_key_id.
   * </pre>
   *
   * <code>uint32 primary_key_id = 1;</code>
   * @return The primaryKeyId.
   */
  int getPrimaryKeyId();

  /**
   * <pre>
   * KeyInfos in the KeysetInfo.
   * Each KeyInfo is corresponding to a Key in the corresponding Keyset.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.KeysetInfo.KeyInfo key_info = 2;</code>
   */
  java.util.List<com.google.crypto.tink.proto.KeysetInfo.KeyInfo> 
      getKeyInfoList();
  /**
   * <pre>
   * KeyInfos in the KeysetInfo.
   * Each KeyInfo is corresponding to a Key in the corresponding Keyset.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.KeysetInfo.KeyInfo key_info = 2;</code>
   */
  com.google.crypto.tink.proto.KeysetInfo.KeyInfo getKeyInfo(int index);
  /**
   * <pre>
   * KeyInfos in the KeysetInfo.
   * Each KeyInfo is corresponding to a Key in the corresponding Keyset.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.KeysetInfo.KeyInfo key_info = 2;</code>
   */
  int getKeyInfoCount();
  /**
   * <pre>
   * KeyInfos in the KeysetInfo.
   * Each KeyInfo is corresponding to a Key in the corresponding Keyset.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.KeysetInfo.KeyInfo key_info = 2;</code>
   */
  java.util.List<? extends com.google.crypto.tink.proto.KeysetInfo.KeyInfoOrBuilder> 
      getKeyInfoOrBuilderList();
  /**
   * <pre>
   * KeyInfos in the KeysetInfo.
   * Each KeyInfo is corresponding to a Key in the corresponding Keyset.
   * </pre>
   *
   * <code>repeated .google.crypto.tink.KeysetInfo.KeyInfo key_info = 2;</code>
   */
  com.google.crypto.tink.proto.KeysetInfo.KeyInfoOrBuilder getKeyInfoOrBuilder(
      int index);
}
