// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/tink.proto

package com.google.crypto.tink.proto;

public final class Tink {
  private Tink() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_KeyTemplate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_KeyTemplate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_KeyData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_KeyData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_Keyset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_Keyset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_Keyset_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_Keyset_Key_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_KeysetInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_KeysetInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_KeysetInfo_KeyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_KeysetInfo_KeyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_EncryptedKeyset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_EncryptedKeyset_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/tink.proto\022\022google.crypto.tink\"p" +
      "\n\013KeyTemplate\022\020\n\010type_url\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\014\022@\n\022output_prefix_type\030\003 \001(\0162$.goo" +
      "gle.crypto.tink.OutputPrefixType\"\350\001\n\007Key" +
      "Data\022\020\n\010type_url\030\001 \001(\t\022\r\n\005value\030\002 \001(\014\022F\n" +
      "\021key_material_type\030\003 \001(\0162+.google.crypto" +
      ".tink.KeyData.KeyMaterialType\"t\n\017KeyMate" +
      "rialType\022\027\n\023UNKNOWN_KEYMATERIAL\020\000\022\r\n\tSYM" +
      "METRIC\020\001\022\026\n\022ASYMMETRIC_PRIVATE\020\002\022\025\n\021ASYM" +
      "METRIC_PUBLIC\020\003\022\n\n\006REMOTE\020\004\"\211\002\n\006Keyset\022\026" +
      "\n\016primary_key_id\030\001 \001(\r\022+\n\003key\030\002 \003(\0132\036.go" +
      "ogle.crypto.tink.Keyset.Key\032\271\001\n\003Key\022-\n\010k" +
      "ey_data\030\001 \001(\0132\033.google.crypto.tink.KeyDa" +
      "ta\0221\n\006status\030\002 \001(\0162!.google.crypto.tink." +
      "KeyStatusType\022\016\n\006key_id\030\003 \001(\r\022@\n\022output_" +
      "prefix_type\030\004 \001(\0162$.google.crypto.tink.O" +
      "utputPrefixType\"\201\002\n\nKeysetInfo\022\026\n\016primar" +
      "y_key_id\030\001 \001(\r\0228\n\010key_info\030\002 \003(\0132&.googl" +
      "e.crypto.tink.KeysetInfo.KeyInfo\032\240\001\n\007Key" +
      "Info\022\020\n\010type_url\030\001 \001(\t\0221\n\006status\030\002 \001(\0162!" +
      ".google.crypto.tink.KeyStatusType\022\016\n\006key" +
      "_id\030\003 \001(\r\022@\n\022output_prefix_type\030\004 \001(\0162$." +
      "google.crypto.tink.OutputPrefixType\"`\n\017E" +
      "ncryptedKeyset\022\030\n\020encrypted_keyset\030\002 \001(\014" +
      "\0223\n\013keyset_info\030\003 \001(\0132\036.google.crypto.ti" +
      "nk.KeysetInfo*M\n\rKeyStatusType\022\022\n\016UNKNOW" +
      "N_STATUS\020\000\022\013\n\007ENABLED\020\001\022\014\n\010DISABLED\020\002\022\r\n" +
      "\tDESTROYED\020\003*R\n\020OutputPrefixType\022\022\n\016UNKN" +
      "OWN_PREFIX\020\000\022\010\n\004TINK\020\001\022\n\n\006LEGACY\020\002\022\007\n\003RA" +
      "W\020\003\022\013\n\007CRUNCHY\020\004BX\n\034com.google.crypto.ti" +
      "nk.protoP\001Z-github.com/google/tink/go/pr" +
      "oto/tink_go_proto\242\002\006TINKPBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_crypto_tink_KeyTemplate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_crypto_tink_KeyTemplate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_KeyTemplate_descriptor,
        new java.lang.String[] { "TypeUrl", "Value", "OutputPrefixType", });
    internal_static_google_crypto_tink_KeyData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_crypto_tink_KeyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_KeyData_descriptor,
        new java.lang.String[] { "TypeUrl", "Value", "KeyMaterialType", });
    internal_static_google_crypto_tink_Keyset_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_crypto_tink_Keyset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_Keyset_descriptor,
        new java.lang.String[] { "PrimaryKeyId", "Key", });
    internal_static_google_crypto_tink_Keyset_Key_descriptor =
      internal_static_google_crypto_tink_Keyset_descriptor.getNestedTypes().get(0);
    internal_static_google_crypto_tink_Keyset_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_Keyset_Key_descriptor,
        new java.lang.String[] { "KeyData", "Status", "KeyId", "OutputPrefixType", });
    internal_static_google_crypto_tink_KeysetInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_crypto_tink_KeysetInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_KeysetInfo_descriptor,
        new java.lang.String[] { "PrimaryKeyId", "KeyInfo", });
    internal_static_google_crypto_tink_KeysetInfo_KeyInfo_descriptor =
      internal_static_google_crypto_tink_KeysetInfo_descriptor.getNestedTypes().get(0);
    internal_static_google_crypto_tink_KeysetInfo_KeyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_KeysetInfo_KeyInfo_descriptor,
        new java.lang.String[] { "TypeUrl", "Status", "KeyId", "OutputPrefixType", });
    internal_static_google_crypto_tink_EncryptedKeyset_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_crypto_tink_EncryptedKeyset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_EncryptedKeyset_descriptor,
        new java.lang.String[] { "EncryptedKeyset", "KeysetInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
