// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/xchacha20_poly1305.proto

package com.google.crypto.tink.proto;

public interface XChaCha20Poly1305KeyFormatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.XChaCha20Poly1305KeyFormat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();
}
