// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/xchacha20_poly1305.proto

package com.google.crypto.tink.proto;

public interface XChaCha20Poly1305KeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.crypto.tink.XChaCha20Poly1305Key)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>bytes key_value = 3;</code>
   * @return The keyValue.
   */
  com.google.protobuf.ByteString getKeyValue();
}
