// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/xchacha20_poly1305.proto

package com.google.crypto.tink.proto;

public final class Xchacha20Poly1305 {
  private Xchacha20Poly1305() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_XChaCha20Poly1305KeyFormat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_XChaCha20Poly1305KeyFormat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_crypto_tink_XChaCha20Poly1305Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_crypto_tink_XChaCha20Poly1305Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/xchacha20_poly1305.proto\022\022google" +
      ".crypto.tink\"-\n\032XChaCha20Poly1305KeyForm" +
      "at\022\017\n\007version\030\001 \001(\r\":\n\024XChaCha20Poly1305" +
      "Key\022\017\n\007version\030\001 \001(\r\022\021\n\tkey_value\030\003 \001(\014B" +
      "]\n\034com.google.crypto.tink.protoP\001Z;githu" +
      "b.com/google/tink/go/proto/xchacha20_pol" +
      "y1305_go_protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_crypto_tink_XChaCha20Poly1305KeyFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_crypto_tink_XChaCha20Poly1305KeyFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_XChaCha20Poly1305KeyFormat_descriptor,
        new java.lang.String[] { "Version", });
    internal_static_google_crypto_tink_XChaCha20Poly1305Key_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_crypto_tink_XChaCha20Poly1305Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_crypto_tink_XChaCha20Poly1305Key_descriptor,
        new java.lang.String[] { "Version", "KeyValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
